### ISSUE TITLE
How to set date field empty until user chooses a date ?

### ISSUE THREAD

**Issue by Centeos** [hashiprobr/react-native-paper-datetimepicker#1]
Hi, i am new to React Native, please let me know how to set date field empty until user chooses a date, means in my case date is optional.

**Comment by hashiprobr** [comment]
Hi, this is not currently supported, but it doesn't seem particularly hard to implement. I'll keep you updated.

**Comment by hashiprobr** [comment]
Version 1.1.20 allows empty values.
